<?php
echo '<!DOCTYPE html>';
echo '<html lang="es">';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta content="width=device-width, initial-scale=1" name="viewport">';
echo '';
echo '<title>A & A games</title>';
echo '<link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;800&display=swap" rel="stylesheet">';
echo '<link rel="stylesheet" href="css/style.css" >';
echo '';
echo '</head>';
echo '<body>';
echo '<div style="background-color: black; display: table;">';
echo '<a href=".\menu.html">';
echo '<img src=".\img\AA Games Logo Claro.png" style="width: 12%">';
echo '</a>';
echo '<a style="padding: 0px 0px 0px 585px;">';
echo '<img src=".\img\Andy.png" style="width: 15%">';
echo '</a>';
echo '<a href="https://www.facebook.com/andyali.rivadeneyrarobles/">';
echo '<img src=".\img\facebook.png">';
echo '</a>';
echo '<a href="https://www.instagram.com/andy_rivadeneyra/">';
echo '<img src=".\img\instagram.png">';
echo '</a>';
echo '<a>';
echo '<img src=".\img\Anthony.png" style="width: 15%">';
echo '</a>';
echo '<a href="https://www.facebook.com/NoLimitsFunn">';
echo '<img src=".\img\facebook.png">';
echo '</a>';
echo '<a href="https://www.instagram.com/thehalo172/">';
echo '<img src=".\img\instagram.png">';
echo '</a>';
echo '</div>';
echo '<div style="background-color: #ffffff">';
echo '<a>';
echo '<img src=".\img\AA Games.png" class="logo">';
echo '</a>';
echo '<a href=".\productos.html">';
echo '<img src=".\img\boton.png" style="width: 50%">';
echo '</a>';
echo '</div>';
echo '<footer>';
echo 'A&A Games 2021 | Todos los Derechos Reservados';
echo '</footer>';
echo '</body>';
echo '</html>';
?>